import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";

const Nohemi = localFont({
  src: [
    {
      path: '../public/fonts/Nohemi-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
     {
      path: '../public/fonts/Nohemi-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Nohemi-Bold.woff2',
      weight: '800',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${Nohemi.className} antialiased`}
      >
        <Toaster richColors closeButton position="top-center" />
            <ThemeProvider
                     attribute="class"
                     defaultTheme="light"
                     enableSystem
                     disableTransitionOnChange>
        {children}
        
        </ThemeProvider>
      </body>
    </html>
  );
}
